# Generated by Django 4.2.11 on 2026-07-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=80, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('thana', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], db_index=True, default='owner', help_text='Controls discount permission and supervisor override in POS.', max_length=20)),
                ('is_first_login', models.BooleanField(default=False)),
                ('profile_picture', models.URLField(blank=True, default='', help_text="Absolute URL of the user's avatar. Empty = fall back to initials.", max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of each finalized sale credited to this user.', max_digits=5, null=True)),
                ('max_sales_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Highest discount % this user can apply without supervisor approval.', max_digits=5, null=True)),
                ('allow_selected_contacts', models.BooleanField(default=False, help_text='Restrict this user to selling only to a fixed customer list.')),
                ('allowed_contact_ids', models.JSONField(blank=True, default=list, help_text='Customer UUIDs the user can sell to. Empty = no restriction.')),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('force_logout_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent_owner', models.ForeignKey(blank=True, help_text='Owner this sub-user reports to. NULL for owners.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rbac_permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Owner this custom role belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_roles',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('password_set', 'Password set/reset'), ('admin_action', 'Admin action')], db_index=True, max_length=24)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('target', models.CharField(blank=True, default='', max_length=254)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='secevt_event_time_idx'), models.Index(fields=['actor_id', 'created_at'], name='secevt_actor_time_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.tenantrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.UUIDField(db_index=True)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_branches',
                'unique_together': {('user', 'branch_id')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], db_index=True, help_text='Role code — must match one of User.Role choice values.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
            ],
            options={
                'db_table': 'rbac_role_permissions',
                'ordering': ['role_code', 'permission__code'],
                'unique_together': {('role_code', 'permission')},
            },
        ),
    ]
