# Generated by Django 4.2.11 on 2026-04-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(help_text="Physical PostgreSQL database name, e.g. 'saas_tenant_e2c4eb3406d7'.", max_length=128, unique=True)),
                ('db_alias', models.CharField(help_text="Django DATABASES key, e.g. 'tenant_e2c4eb3406d7'.", max_length=128, unique=True)),
                ('is_provisioned', models.BooleanField(db_index=True, default=False, help_text='True once the physical DB is created and migrations are applied.')),
                ('provisioned_at', models.DateTimeField(blank=True, help_text='Timestamp when provisioning completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='One tenant record per user.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
