# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(help_text='Full message body. Supports {variable} substitution.'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(blank=True, help_text='Used for email/SMS. Supports {variable} substitution.', max_length=500),
        ),
    ]
