# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='Numeric code (e.g. 1001). Unique across the tenant.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_contra',
            field=models.BooleanField(default=False, help_text='Contra-accounts have the opposite normal balance of their type. Example: Sales Discounts (INCOME type, DEBIT normal balance).'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System accounts are seeded automatically and cannot be deleted.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by_id',
            field=models.UUIDField(help_text='UUID of the User who recorded this expense.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(help_text='Expense / COGS account that is debited.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_as_expense', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(help_text='Cash / Bank / Mobile account that is credited.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_as_payment', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by_id',
            field=models.UUIDField(blank=True, help_text='UUID of the User who triggered this entry.', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(help_text='Sequential per-month identifier, e.g. JE-202604-0001.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=True, help_text='Posted entries are final and cannot be edited.'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the source document (Sale, Expense, …).', null=True),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
