# Generated by Django 4.2.11 on 2026-04-21 07:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, default=inventory.models._generate_sku, help_text='Auto-generated if not provided. Format: SKU-XXXXXXXX.', max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN-13 or other barcode. Auto-generated on request.', max_length=20, null=True, unique=True)),
                ('warranty_days', models.PositiveIntegerField(default=0, help_text='Warranty period in days. 0 = no warranty.')),
                ('selling_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Adjustment')], db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Always positive. Direction implied by movement_type.', max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Cost per unit at time of movement.', max_digits=14, null=True)),
                ('cogs', models.DecimalField(blank=True, decimal_places=4, help_text='FIFO-computed COGS for OUT movements.', max_digits=14, null=True)),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='mov_product_date_idx'), models.Index(fields=['location', 'created_at'], name='mov_location_date_idx'), models.Index(fields=['reference_type', 'reference_id'], name='mov_reference_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current on-hand quantity at this location.', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
            ],
            options={
                'db_table': 'product_stocks',
                'ordering': ['product', 'location'],
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='FIFOLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_qty', models.DecimalField(decimal_places=4, help_text='Quantity at creation. Never modified after creation.', max_digits=14)),
                ('remaining_qty', models.DecimalField(decimal_places=4, help_text='Remaining unconsumed quantity. Decreases as stock is sold.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, help_text='Purchase cost per unit. Used for COGS calculation.', max_digits=14)),
                ('reference_type', models.CharField(blank=True, db_index=True, help_text="Source document type: 'purchase', 'import', 'adjustment'.", max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='Source document UUID.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='FIFO order key. Set to purchase date for backdated imports.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Where this batch was received (audit only — FIFO deduction is global).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifo_layers', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_layers', to='inventory.product')),
            ],
            options={
                'db_table': 'fifo_layers',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='fifo_product_date_idx'), models.Index(fields=['product', 'remaining_qty'], name='fifo_product_qty_idx')],
            },
        ),
    ]
