# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_reorder_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_idx',
        ),
    ]
