# Generated by Django 4.2.11 on 2026-04-22 05:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_product_name_idx_and_more'),
        ('sales', '0002_customer_soft_delete'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_name_del_idx',
        ),
        migrations.AlterField(
            model_name='backorder',
            name='available_qty',
            field=models.DecimalField(decimal_places=4, help_text='Stock on hand at the time the back-order was raised.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='backorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='backorder',
            name='requested_qty',
            field=models.DecimalField(decimal_places=4, help_text='Quantity the customer ordered.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='backorder',
            name='shortfall_qty',
            field=models.DecimalField(decimal_places=4, help_text='requested_qty − available_qty', max_digits=14),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, help_text='VAT / GST / TIN number for invoice.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total_amount − amount_paid', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by_id',
            field=models.UUIDField(help_text='UUID of the User who created this sale.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='NULL = walk-in / anonymous sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total header-level discount applied to subtotal.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='finalized_by_id',
            field=models.UUIDField(blank=True, help_text='UUID of the User who finalized this sale.', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Set on finalization. Format: INV-YYYYMM-NNNN', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(help_text='Which branch/warehouse this sale is fulfilled from.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of (unit_price × quantity) for all line items.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax percentage (e.g. 15.00 = 15 %).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='(subtotal − discount) + tax_amount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost of goods sold — computed by FIFO engine on finalization.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Per-unit flat discount (reduces unit price before qty multiply).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='(unit_price − item_discount) × quantity', max_digits=14),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='received_by_id',
            field=models.UUIDField(help_text='UUID of the User (cashier/staff) who received this payment.'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Card auth code, bank ref, mobile transaction ID, etc.', max_length=100),
        ),
    ]
