# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations, models
import imports.models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='created_by_id',
            field=models.UUIDField(db_index=True, help_text='UUID of the User who uploaded this file.'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=imports.models._default_expires_at, help_text='Batch row is safe to prune after this datetime.'),
        ),
    ]
