# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(db_index=True, help_text="Dot-separated key, e.g. 'currency.symbol'.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_by_id',
            field=models.UUIDField(blank=True, help_text='UUID of the User who last changed this setting.', null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value_str',
            field=models.TextField(help_text='Stored as text; see value_type for how to interpret.'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Only one TaxGroup should be marked as default.'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Tax rate as a percentage, e.g. 15.0000 for 15%.', max_digits=6),
        ),
    ]
