# Generated by Django 4.2.11 on 2026-04-22 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Any additional context (e.g. endpoint, query params).'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, help_text="App and model name, e.g. 'inventory.Product'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, help_text='Serialized state AFTER the action (null for DELETE).', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, help_text='Serialized state BEFORE the action (null for CREATE).', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Primary key of the affected record.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_repr',
            field=models.CharField(blank=True, help_text='Human-readable representation of the record at action time.', max_length=300),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the User (from master DB) who performed the action.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, help_text="Snapshot of the user's name at the time of the action.", max_length=200),
        ),
    ]
